### PR TITLE
Adds french translation

### PR DESCRIPTION
**Pull request by gottfrois**
Hey there, thanks for the great website!

Here is a small contribution to make it even better in french.
Keep up the good work!

### CODE REVIEW

**Comment by queicherius** [comment]
Thank you very much!

Could you please add yourself to the list [here](https://github.com/gw2efficiency/translations/blob/master/credits.js#L4) with your GW2 account name? That way your name will show up with the translators [here](https://gw2efficiency.com/community/contributors). :)

**Comment by EDCDragon** [comment]
Hello, this commit contains some errors: 

"Adept (300 - 399)": "Adèpte (300 - 399)",
"Adept (300 - 399)": "Adepte (300 - 399)",

"Legendary Component": "Composent légendaire",
"Legendary Component": "Composant légendaire",

  "You have unlocked {currentUnlockCount} of {totalUnlockCount} ({unlockPercentage}) {unlockTypeName} matching the current filters.": "Vous avez débloqué {currentUnlockCount} sur {totalUnlockCount} ({unlockPercentage}) {unlockTypeName} correspondant aux filtres actuels.",
  "You have unlocked {currentUnlockCount} of {totalUnlockCount} ({unlockPercentage}) {unlockTypeName} matching the current filters.": "Vous avez débloqué {currentUnlockCount} sur {totalUnlockCount} ({unlockPercentage}) {unlockTypeName} correspondants aux filtres actuels.",

"finishers": "coûps de grâce",
"finishers": "coups de grâce",

  "gliders": "planneurs",
  "gliders": "deltaplane",

  "mailcarriers": "courriers",
  "mailcarriers": "messagers",

**Comment by gottfrois** [comment]
Thanks mate for the second pair of eyes!

**Comment by gottfrois** [comment]
@queicherius I fixed the translations based on @EDCDragon feedback and added myself in the credits, PR should be good to merge 👍

**Comment by queicherius** [comment]
Appreciate it! 👍

**Pull request merged**
